"""
Django settings for test_1 project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url # type: ignore

# Environment Distinction
ENVIRONMENT = os.getenv("ENVIRONMENT", '')



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv(os.path.join(BASE_DIR, ".env"))
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == "production":
    DEBUG = False
elif ENVIRONMENT == "staging":
    DEBUG = True
else:
     DEBUG = True

if ENVIRONMENT == "production":
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'hosthub.160maincarryout.com'
    ]
elif ENVIRONMENT == 'staging':
     ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'devhosthub.160maincarryout.com'
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'testendpoint',
    'hosthub',
    "staff.apps.StaffConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'test_1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test_1.wsgi.application'

LOGIN_URL = '/test/login/'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': env('POSTGRES_NAME'),
#         "USER": env('POSTGRES_USER'),
#         "PASSWORD": env("POSTGRES_PASSWORD"),
#         "HOST": env("POSTGRES_HOST"),
#         "PORT": env("POSTGRES_PORT"),
#     }
# }


DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
        )
    }
else:
        DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('POSTGRES_NAME'),
            "USER": env('POSTGRES_USER'),
            "PASSWORD": env("POSTGRES_PASSWORD"),
            "HOST": env("POSTGRES_HOST"),
            "PORT": env("POSTGRES_PORT"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Detroit'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BLAND_API_KEY = os.environ.get("BLAND_API_KEY", "")

if ENVIRONMENT == "production":
    CSRF_TRUSTED_ORIGINS = [
        'https://hosthub.160maincarryout.com'
    ]
elif ENVIRONMENT == "staging":
     CSRF_TRUSTED_ORIGINS = [
        'https://devhosthub.160maincarryout.com'
    ]

DASHBOARD_PIN = os.environ.get("DASHBOARD_PIN", "7983")
BLAND_WEBHOOK_TOKEN = os.environ.get("BLAND_WEBHOOK_TOKEN", "")

BLAND_ORG_ID = os.environ.get("BLAND_ORG_ID", "")

# Endpoint secret to access Carryout Dashboard
CARRYOUT_DASHBOARD_SLUG=os.environ.get("CARRYOUT_DASHBOARD_SLUG", "")

HOSTHUB_SSE_TOKEN = os.environ.get("HOSTHUB_SSE_TOKEN", default="")


#RESEND EMAIL CONFIG
RESEND_API_KEY=os.environ.get("RESEND_API_KEY", default='')
RECIPIENT_EMAIL=os.environ.get("RECIPIENT_EMAIL", default='')
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", default='')
 
