# Generated by Django 5.1.3 on 2025-12-03 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bland_call_id', models.CharField(max_length=250, unique=True)),
                ('from_number', models.CharField(blank=True, max_length=50, null=True)),
                ('to_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('queue_status', models.CharField(blank=True, max_length=50, null=True)),
                ('bland_status', models.CharField(blank=True, max_length=50, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_transcript', models.TextField(blank=True, null=True)),
                ('pathway_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('variables', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('display_category', models.CharField(choices=[('reservation', 'Reservation'), ('carryout', 'Carryout'), ('leave_message', 'Leave a message'), ('other', 'Other')], default='other', max_length=50)),
                ('host_status', models.CharField(choices=[('needs_action', 'Needs Action'), ('resolved', 'Resloved')], default='needs_action', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
