# Generated by Django 5.1.3 on 2025-12-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0002_alter_call_display_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
