# Generated by Django 5.1.3 on 2026-01-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0003_call_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='display_category',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('carryout', 'Carryout'), ('leave_message', 'Leave a message'), ('other', 'Other'), ('private_events', 'Private Events')], default='other', max_length=50),
        ),
    ]
