# Generated by Django 5.1.3 on 2026-01-21 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0004_alter_call_display_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('transferred', 'Transferred'), ('abandoned', 'Abandoned')], db_index=True, default='queued', max_length=20)),
                ('from_number', models.CharField(blank=True, db_index=True, help_text="Caller phone number (from Bland 'from' field)", max_length=30, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-updated_at'], name='testendpoin_status_d63acd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red')], db_index=True, max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=80, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='testendpoint.callsession')),
            ],
            options={
                'indexes': [models.Index(fields=['resolved_at', 'severity', '-created_at'], name='testendpoin_resolve_bccc40_idx'), models.Index(fields=['call', 'resolved_at'], name='testendpoin_call_id_2a441f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TranscriptTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('user', 'User')], db_index=True, max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_turns', to='testendpoint.callsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['call', 'created_at'], name='testendpoin_call_id_c3130d_idx'), models.Index(fields=['call', 'sequence'], name='testendpoin_call_id_b45e82_idx')],
            },
        ),
    ]
