# Generated by Django 5.1.3 on 2026-02-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0005_callsession_callalert_transcriptturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
