# Generated by Django 5.1.3 on 2026-02-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0006_call_ingested_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptturn',
            options={'ordering': ['sequence']},
        ),
        migrations.RemoveIndex(
            model_name='callsession',
            name='testendpoin_status_d63acd_idx',
        ),
        migrations.RemoveIndex(
            model_name='transcriptturn',
            name='testendpoin_call_id_b45e82_idx',
        ),
        migrations.AddField(
            model_name='transcriptturn',
            name='dedupe_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', 'updated_at'], name='testendpoin_status_3ede7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptturn',
            constraint=models.UniqueConstraint(fields=('call', 'sequence'), name='unique_seq_per_call'),
        ),
    ]
