# Generated by Django 5.1.3 on 2026-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0007_alter_transcriptturn_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transcriptturn',
            name='unique_seq_per_call',
        ),
        migrations.AddConstraint(
            model_name='transcriptturn',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence__isnull', False)), fields=('call', 'sequence'), name='unique_seq_per_call'),
        ),
    ]
