# Generated by Django 5.1.3 on 2026-03-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0008_remove_transcriptturn_unique_seq_per_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='transcripts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
