# Generated by Django 5.1.3 on 2026-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0010_call_disposition_call_handled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='disposition',
            field=models.CharField(blank=True, choices=[('reservation_placed', 'Reservation Placed by Host'), ('reservation_link', 'Reservation Placed via Link Sent to Caller'), ('reservation_update', 'Reservation Successfully Updated by Host'), ('reservation_canceled', 'Reservation Canceled by Host'), ('carryout_ai_host', 'Carryout Order Placed via AI Host'), ('carryout_link', 'Carryout Order Placed via Link Sent to Caller'), ('message_handled', 'Message Left by Caller Handled by Host'), ('questions_answered', 'Caller Had Questions That Were Answered by AI Host'), ('private_party', 'Informed Manager About Private Party First Inquiry'), ('private_party_message', 'Informed Manager About Message Left About Existing Private Party'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
