# Generated by Django 5.1.3 on 2026-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0011_alter_call_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='handled_by',
            field=models.CharField(blank=True, choices=[('david', 'David'), ('derek', 'Derek'), ('gabriel', 'Gabriel'), ('brian', 'Brian'), ('miguel', 'Miguel'), ('adiana', 'Adriana')], max_length=20, null=True),
        ),
    ]
