# Generated by Django 5.1.3 on 2026-03-31 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0013_account_location_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='testendpoint.account'),
        ),
        migrations.AddField(
            model_name='call',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='testendpoint.location'),
        ),
        migrations.AddField(
            model_name='call',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='testendpoint.phonenumber'),
        ),
    ]
