# Generated by Django 5.1.3 on 2026-04-02 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0014_call_account_call_location_call_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('host', 'Host')], default='host', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='testendpoint.account')),
                ('locations', models.ManyToManyField(blank=True, related_name='authorized_users', to='testendpoint.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosthub_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
