# Generated by Django 5.1.3 on 2026-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0016_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
