# Generated by Django 5.1.3 on 2026-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0018_call_handled_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='to_number',
            field=models.CharField(blank=True, db_index=True, help_text="Receiver phone number (from Bland 'to' field)", max_length=30, null=True),
        ),
    ]
