# Generated by Django 5.1.3 on 2026-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0019_callsession_to_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pathway_id_closed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pathway_id_open',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
