# Generated by Django 5.1.3 on 2026-04-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0020_location_pathway_id_closed_location_pathway_id_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='pathway_id_closed',
            new_name='bland_pathway_id_closed',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='pathway_id_open',
            new_name='bland_pathway_id_open',
        ),
    ]
