# Generated by Django 5.1.3 on 2026-04-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0021_rename_pathway_id_closed_location_bland_pathway_id_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='location_logos/'),
        ),
    ]
