# Generated by Django 5.1.3 on 2026-04-15 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0022_location_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='expected_pathway_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='scheduling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='testendpoint.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'day_of_week'], name='testendpoin_locatio_35e5f6_idx')],
                'unique_together': {('location', 'day_of_week')},
            },
        ),
    ]
