# Generated by Django 5.1.3 on 2026-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0023_location_expected_pathway_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='expected_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_schedule_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='next_transition_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/Detroit', 'America/Detroit'), ('America/Chicago', 'America/Chicago'), ('America/Denver', 'America/Denver'), ('America/Los_Angeles', 'America/Los_Angeles'), ('Pacific/Honolulu', 'Pacific/Honolulu')], default='UTC', max_length=50),
        ),
    ]
