# Generated by Django 5.1.3 on 2026-04-16 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0024_location_expected_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='manual_override_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='manual_override_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='manual_override_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='manual_override_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
