# Generated by Django 5.1.3 on 2026-04-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0025_location_manual_override_set_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_schedule_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
