# Generated by Django 5.1.3 on 2026-04-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0026_location_last_schedule_evaluated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_pathway_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_synced_pathway_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_synced_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=20, null=True),
        ),
    ]
