# Generated by Django 5.1.3 on 2026-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0027_location_last_pathway_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='daily_report_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Report Email'),
        ),
        migrations.AddField(
            model_name='account',
            name='daily_report_email_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
