# Generated by Django 5.1.3 on 2026-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0028_account_daily_report_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='login_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
