# Generated by Django 5.1.3 on 2026-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0029_account_login_password_hash_account_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='transfer_number',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Transfer Phone Number'),
        ),
    ]
