# Generated by Django 5.1.3 on 2026-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0030_location_transfer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='transfer_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Transfer Phone Number'),
        ),
    ]
