# Generated by Django 5.1.3 on 2026-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0032_alter_location_transfer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='transfer_target',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OnSip Target'),
        ),
    ]
