# Generated by Django 5.1.3 on 2026-06-08 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0033_location_transfer_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='disposition',
            field=models.CharField(blank=True, choices=[('reservation_placed', 'Reservation Placed by Host'), ('reservation_confirmed', 'Reservation Confirmed with Caller'), ('reservation_link', 'Reservation Placed via Link Sent to Caller'), ('reservation_update', 'Reservation Successfully Updated by Host'), ('reservation_canceled', 'Reservation Canceled by Host'), ('carryout_ai_host', 'Carryout Order Placed via AI Host'), ('carryout_link', 'Carryout Order Placed via Link Sent to Caller'), ('message_handled', 'Message Left by Caller Handled by Host'), ('questions_answered', 'Caller Had Questions That Were Answered by AI Host'), ('private_party', 'Informed Manager About Private Party First Inquiry'), ('private_party_message', 'Informed Manager About Message Left About Existing Private Party'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_overrides', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='testendpoint.location')),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['location', 'start_date', 'end_date'], name='testendpoin_locatio_cae5c5_idx')],
            },
        ),
    ]
