# Generated by Django 5.1.3 on 2026-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testendpoint', '0034_alter_call_disposition_dateoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='recovery_sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='When a carryout cart recovery SMS was sent to the caller', null=True),
        ),
    ]
